name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: '@epigosai/epigos-sdk'
    steps:
      - name: release please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: ${{ env.PACKAGE_NAME }}
          extra-files: |
            src/version.ts

      - name: fetch code
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install NodeJS
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 16

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install

      - name: publish release
        if: ${{ steps.release.outputs.release_created }}
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
